### ISSUE TITLE
@license-cop/permissive@1.6.3 does not contain .licenses.jsonc

### ISSUE THREAD

**Issue by ben-eb** [tobysmith568/license-cop#180]
Hello 👋 

Thanks again for your work on this project. When installing the new version I noticed that the `.licenses.jsonc` file was missing from the npm package, wanted to let you know.

Workaround is to pin `@license-cop/permissive` to `1.6.2`. 👍 

Thanks!

**Comment by tobysmith568** [comment]
Hey @ben-eb,

What an embarrassing regression!
However I don't feel too bad since this was caused by GitHub introducing a breaking change in their `@actions/upload-artifact` action [_without_ bumping the major version](https://github.com/actions/upload-artifact/issues/602) 🙄

I've resolved this in PR #182 and deployed it in version 1.6.4.
